# Generated by Django 4.1.7 on 2023-02-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(default='About Temp', max_length=1023),
            preserve_default=False,
        ),
    ]
