# Generated by Django 4.1.7 on 2023-02-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=127)),
                ('message', models.CharField(blank=True, max_length=511, null=True)),
                ('status', models.CharField(default='Pending', max_length=31)),
                ('payment_id', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('signature', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(default='Pending', max_length=63),
        ),
    ]
