# Generated by Django 4.1.7 on 2023-02-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_donation_message_alter_animal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
